# Default values for hubone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ihsenbouallegue/hubone
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  env:
    DATABASE_URL: postgresql://postgres:postgres@huboneapp-postgres:5432/hubone

imagePullSecrets: []
nameOverride: "huboneapp"
fullnameOverride: "huboneapp"


service:
  type: NodePort
  port: 3000

route:
  enabled: false
  path: user.huboneapp.com
  parentrefs:
    name: "hubone-gateway"
    namespace: "default"

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: user.hubone.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

postgresql:
  fullnameOverride: huboneapp-postgres
  auth:
    postgresPassword: postgres
    username: postgres
    password: postgres
    database: hubone
  primary:
    podSecurityContext:
      enabled: false
      fsGroup: ""
    containerSecurityContext:
      enabled: false
      runAsUser: "auto"

  readReplicas:
    podSecurityContext:
      enabled: false
      fsGroup: ""
    containerSecurityContext:
      enabled: false
      runAsUser: "auto"

  volumePermissions:
    enabled: true
    securityContext:
      runAsUser: "auto"