# Default values for hubone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ihsenbouallegue/hubone
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  env:
    DATABASE_URL: postgresql://postgres:postgres@postgresql-service:5432/hubone

imagePullSecrets: []
nameOverride: "hubone-app"
fullnameOverride: "hubone-chart"

podAnnotations:
  argocd.argoproj.io/sync-wave: "2"

service:
  type: NodePort
  port: 3000
  annotations:
    argocd.argoproj.io/sync-wave: "2"

route:
  enabled: false
  path: user.huboneapp.com
  parentrefs:
    name: "hubone-gateway"
    namespace: "default"

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    argocd.argoproj.io/sync-wave: "3"

  hosts:
    - host: user.huboneapp.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
