apiVersion: batch/v1
kind: Job
metadata:
  name: hubone-schema-hook
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: hubone-schema-container
        image: ihsenbouallegue/hubone-schema:latest
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            value: postgresql://postgres:postgres@postgresql-service:5432/hubone
        command: ["/bin/sh"]
        args: ["-c", "npx prisma migrate deploy | npx prisma db seed"]
      restartPolicy: Never
  backoffLimit: 1