apiVersion: batch/v1
kind: Job
metadata:
  name: hubone-schema-hook
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: hubone-schema-container
        image: ihsenbouallegue/hubone-schema:latest
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            value: {{ .Values.image.env.DATABASE_URL}}
        command: ["/bin/sh"]
        args: ["-c", "npx prisma migrate deploy | npx prisma db seed"]
      restartPolicy: Never
  backoffLimit: 1