apiVersion: v1
kind: Service
metadata:
  name: {{ include "hubone.fullname" . }}
  labels:
    {{- include "hubone.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "hubone.selectorLabels" . | nindent 4 }}
